sudo: false
dist: xenial
language: csharp
mono: none
dotnet: 2.2
solution: Com.DanLiris.Service.Packing.Inventory.sln
env:
    - ASPNETCORE_ENVIRONMENT=Test

before_install:
    
install: true

before_script:

script:
    - dotnet restore --verbosity normal
    - dotnet build
    - dotnet test src/Com.DanLiris.Service.Packing.Inventory.Test/Com.DanLiris.Service.Packing.Inventory.Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=lcov

after_success:
    - curl -s https://codecov.io/bash > codecov
    - chmod +x codecov
    - ./codecov -f "/home/travis/build/danliris/com-danliris-service-packing-inventory/src/Com.DanLiris.Service.Packing.Inventory.Test/coverage.info"
